/* ================================================
   PROPERTY DETAIL – property-detail.js
   ================================================ */
document.addEventListener('DOMContentLoaded', () => {

  /* ================================================
     SLIDER
     ================================================ */
  // Read images directly from the HTML slides generated by Sanity
const slideEls = document.querySelectorAll('#sliderTrack .pd-slide img');
const images = Array.from(slideEls).map((img, i) => ({
  src: img.getAttribute('src'),
  label: img.getAttribute('alt') || `Photo ${i + 1}`
}));

// If no slides found stop here
if (images.length === 0) return;

  const track      = document.getElementById('sliderTrack');
  const dotsWrap   = document.getElementById('sliderDots');
  const thumbStrip = document.getElementById('thumbStrip');
  const counter    = document.getElementById('sliderCounter');
  const prevBtn    = document.getElementById('sliderPrev');
  const nextBtn    = document.getElementById('sliderNext');
  window.currentSlide = 0;

  // Build dots
  images.forEach((_, i) => {
    const dot = document.createElement('button');
    dot.className = 'pd-dot' + (i === 0 ? ' active' : '');
    dot.addEventListener('click', () => goTo(i));
    dotsWrap.appendChild(dot);
  });

  // Build thumbnail strip
  images.forEach((img, i) => {
    const th = document.createElement('div');
    th.className = 'pd-strip-thumb' + (i === 0 ? ' active' : '');
    th.innerHTML = `<img src="${img.src.replace('w=1400', 'w=160')}" alt="${img.label}" loading="lazy" />`;
    th.addEventListener('click', () => goTo(i));
    thumbStrip.appendChild(th);
  });

  function goTo(idx) {
    window.currentSlide = (idx + images.length) % images.length;
    track.style.transform = `translateX(-${window.currentSlide * 100}%)`;
    // Update counter
    if (counter) counter.textContent = `${window.currentSlide + 1} / ${images.length}`;
    // Update dots
    dotsWrap.querySelectorAll('.pd-dot').forEach((d, i) => d.classList.toggle('active', i === window.currentSlide));
    // Update thumbs
    thumbStrip.querySelectorAll('.pd-strip-thumb').forEach((t, i) => {
      t.classList.toggle('active', i === window.currentSlide);
      if (i === window.currentSlide) t.scrollIntoView({ block: 'nearest', inline: 'nearest' });
    });
  }

  if (prevBtn) prevBtn.addEventListener('click', () => goTo(window.currentSlide - 1));
  if (nextBtn) nextBtn.addEventListener('click', () => goTo(window.currentSlide + 1));

  // Touch / swipe support
  let touchStartX = 0;
  if (track) {
    track.addEventListener('touchstart', e => { touchStartX = e.touches[0].clientX; }, { passive: true });
    track.addEventListener('touchend', e => {
      const diff = touchStartX - e.changedTouches[0].clientX;
      if (Math.abs(diff) > 50) goTo(window.currentSlide + (diff > 0 ? 1 : -1));
    });
  }

//   // Auto-advance every 6 seconds
//   let autoTimer = setInterval(() => goTo(window.currentSlide + 1), 6000);
//   [prevBtn, nextBtn].forEach(btn => btn?.addEventListener('click', () => { clearInterval(autoTimer); autoTimer = setInterval(() => goTo(window.currentSlide + 1), 6000); }));

  /* ================================================
     LIGHTBOX
     ================================================ */
  const lightbox = document.getElementById('lightbox');
  const lbImg     = document.getElementById('lbImg');
  const lbCounter = document.getElementById('lbCounter');
  let lbIdx = 0;

  function updateLb() {
    if (lbImg) lbImg.src = images[lbIdx].src;
    if (lbCounter) lbCounter.textContent = `${lbIdx + 1} / ${images.length}`;
  }
  window.openLightbox = function(idx) {
    lbIdx = idx ?? window.currentSlide;
    updateLb();
    if (lightbox) { lightbox.classList.add('open'); document.body.style.overflow = 'hidden'; }
  };
  window.closeLightbox = function() {
    if (lightbox) { lightbox.classList.remove('open'); document.body.style.overflow = ''; }
  };
  window.lbNav = function(dir) { lbIdx = (lbIdx + dir + images.length) % images.length; updateLb(); };
  if (lightbox) lightbox.addEventListener('click', e => { if (e.target === lightbox) closeLightbox(); });
  document.addEventListener('keydown', e => {
    if (!lightbox?.classList.contains('open')) return;
    if (e.key === 'Escape') closeLightbox();
    if (e.key === 'ArrowRight') lbNav(1);
    if (e.key === 'ArrowLeft')  lbNav(-1);
  });

  /* ================================================
     NAVBAR – transparent over slider, white on scroll
     The slider section's padding-top: 120px creates the offset.
     script.js handles the general logo swap; here we just
     ensure the gallery section triggers transparency correctly.
     ================================================ */
  // script.js already handles #navbar .scrolled class + logo swap.
  // No extra code needed — it works identically to sproperties.html.

  /* ================================================
     TABS
     ================================================ */
  document.querySelectorAll('.pd-tab-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      document.querySelectorAll('.pd-tab-btn').forEach(b => b.classList.remove('active'));
      document.querySelectorAll('.pd-tab-content').forEach(c => c.classList.remove('active'));
      btn.classList.add('active');
      document.getElementById(`tab-${btn.dataset.tab}`)?.classList.add('active');
    });
  });

  /* ================================================
     READ MORE / LESS
     ================================================ */
  window.toggleDesc = function() {
    const more = document.getElementById('descMore');
    const btn  = document.getElementById('readMoreBtn');
    const open = more?.style.display !== 'none';
    if (more) more.style.display = open ? 'none' : 'block';
    if (btn) btn.innerHTML = open
      ? 'Read More <i class="fa fa-chevron-down ml-1"></i>'
      : 'Read Less <i class="fa fa-chevron-up ml-1"></i>';
  };

  /* ================================================
     FLOOR PLAN SWITCHER
     ================================================ */
  window.switchFloor = function(btn, floorId) {
    document.querySelectorAll('.pd-fp-btn').forEach(b => b.classList.remove('active'));
    document.querySelectorAll('.pd-fp-plan').forEach(p => p.classList.remove('active'));
    btn.classList.add('active');
    document.getElementById(`floor-${floorId}`)?.classList.add('active');
  };

  /* ================================================
     WISHLIST
     ================================================ */
  let wishlisted = false;
  function setWishlist(state) {
    wishlisted = state;
    const topBtn  = document.getElementById('wishlistTopBtn');
    const sideBtn = document.getElementById('wishlistSideBtn');
    [topBtn, sideBtn].forEach(btn => {
      if (!btn) return;
      btn.innerHTML = wishlisted
        ? '<i class="fa fa-heart mr-1.5" style="color:var(--primary)"></i> Saved'
        : (btn.id === 'wishlistTopBtn' ? '<i class="fa fa-heart mr-1.5"></i> Save' : '<i class="fa fa-heart mr-2"></i> Save to Wishlist');
      btn.classList.toggle('saved', wishlisted);
    });
  }
  window.toggleWishlist = function() { setWishlist(!wishlisted); showToast(wishlisted ? '❤️ Saved to wishlist!' : '💔 Removed from wishlist'); };
  document.getElementById('wishlistTopBtn')?.addEventListener('click', () => toggleWishlist());

  /* ================================================
     SHARE
     ================================================ */
  window.shareProperty = function() {
    if (navigator.share) {
      navigator.share({ title: 'Signature Palm Villa – HomeKeys Real Estate', url: window.location.href });
    } else {
      navigator.clipboard.writeText(window.location.href).then(() => showToast('🔗 Link copied!'));
    }
  };

  /* ================================================
     MORTGAGE CALCULATOR
     ================================================ */
  function formatAED(n) { return 'AED ' + Math.round(n).toLocaleString(); }
  window.calcMortgage = function() {
    const price   = parseFloat(document.getElementById('mortPrice')?.value) || 0;
    const down    = parseFloat(document.getElementById('mortDown')?.value)  || 20;
    const rate    = parseFloat(document.getElementById('mortRate')?.value)  || 4.5;
    const term    = parseFloat(document.getElementById('mortTerm')?.value)  || 25;
    const downAmt = price * (down / 100);
    const loan    = price - downAmt;
    const monthly = rate > 0
      ? loan * ((rate / 1200) * Math.pow(1 + rate / 1200, term * 12)) / (Math.pow(1 + rate / 1200, term * 12) - 1)
      : loan / (term * 12);
    const el = id => document.getElementById(id);
    if (el('mortLoan'))    el('mortLoan').textContent    = formatAED(loan);
    if (el('mortMonthly')) el('mortMonthly').textContent = formatAED(monthly) + ' / mo';
    if (el('mortDownAmt')) el('mortDownAmt').textContent = formatAED(downAmt);
  };
  calcMortgage();
  ['mortPrice','mortDown','mortRate','mortTerm'].forEach(id => document.getElementById(id)?.addEventListener('input', calcMortgage));

  /* ================================================
     ENQUIRY FORM
     ================================================ */
  document.getElementById('enquiryForm')?.addEventListener('submit', e => {
    e.preventDefault();
    const btn = e.target.querySelector('.pd-enquiry-submit');
    const orig = btn.innerHTML;
    btn.innerHTML = '<i class="fa fa-spinner fa-spin mr-2"></i> Sending...';
    btn.disabled = true;
    setTimeout(() => {
      btn.innerHTML = '<i class="fa fa-check mr-2"></i> Message Sent!';
      btn.style.background = '#22C55E';
      showToast('✅ Enquiry sent! We\'ll contact you shortly.');
      e.target.reset();
      setTimeout(() => { btn.innerHTML = orig; btn.style.background = ''; btn.disabled = false; }, 3000);
    }, 1500);
  });

  /* ================================================
     NEWSLETTER
     ================================================ */
  document.getElementById('newsletterForm')?.addEventListener('submit', e => {
    e.preventDefault(); showToast('🎉 Subscribed!'); e.target.reset();
  });

  /* ================================================
     BACK TO TOP
     ================================================ */
  const backToTop = document.getElementById('backToTop');
  window.addEventListener('scroll', () => backToTop?.classList.toggle('visible', window.scrollY > 500));
  backToTop?.addEventListener('click', () => window.scrollTo({ top: 0, behavior: 'smooth' }));

  /* ================================================
     SCROLL REVEAL
     ================================================ */
  const obs = new IntersectionObserver(entries => {
    entries.forEach(e => { if (e.isIntersecting) { e.target.style.opacity='1'; e.target.style.transform='translateY(0)'; obs.unobserve(e.target); } });
  }, { threshold: 0.08 });
  document.querySelectorAll('.pd-section, .pd-title-block, .pd-quick-stats, .pd-tabs-nav').forEach((el, i) => {
    el.style.opacity = '0'; el.style.transform = 'translateY(16px)';
    el.style.transition = `opacity 0.45s ease ${i*0.06}s, transform 0.45s ease ${i*0.06}s`;
    obs.observe(el);
  });

  /* ================================================
     TOAST
     ================================================ */
  function showToast(msg) {
    document.querySelector('.toast')?.remove();
    const t = document.createElement('div');
    t.className = 'toast'; t.textContent = msg;
    document.body.appendChild(t);
    setTimeout(() => t.classList.add('show'), 80);
    setTimeout(() => { t.classList.remove('show'); setTimeout(() => t.remove(), 400); }, 3400);
  }

  console.log('🏡 Property detail page loaded');
});